FROM python:3.9-slim-buster

COPY app/ .
COPY requirements.txt .

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

RUN pip install -r requirements.txt

CMD ["/bin/bash", "././init-docker.sh"]
